import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, "..", "..")
const config = JSON.parse(readFileSync(join(__dirname, "config.json"), "utf-8"))
const gitignore = readFileSync(join(root, ".gitignore"), "utf-8")

const files = {
  prettier: { path: join(root, ".prettierignore"), label: "Prettier" },
  stylelint: { path: join(root, ".stylelintignore"), label: "Stylelint" },
}

function build(label, extra) {
  const lines = []

  lines.push(`# ${label} ignore file`)
  lines.push(`# Auto-generated by scripts/ignorefiles/generate.mjs`)
  lines.push(
    `# Do not edit manually — update .gitignore or config.json instead`,
  )
  lines.push("")
  lines.push("##########################")
  lines.push(`# Base (from .gitignore)`)
  lines.push("##########################")
  lines.push("")
  lines.push(gitignore.trim())

  if (extra.length > 0) {
    lines.push("")
    lines.push("##########################")
    lines.push(`# ${label}-specific`)
    lines.push("##########################")
    lines.push("")

    for (const line of extra) {
      lines.push(line)
    }
  }

  lines.push("")
  return lines.join("\n")
}

for (const [key, file] of Object.entries(files)) {
  const extra = config[key] || []
  const content = build(file.label, extra)
  writeFileSync(file.path, content, "utf-8")
  console.log(`Generated ${file.label}: ${file.path}`)
}
